# SonarCloud Project Configuration
sonar.projectKey=ClosetAI_main
sonar.organization=closetai-org

# Path to the source directories
sonar.sources=ai-suggestion-server,my-app/src
sonar.tests=ai-suggestion-server/tests,my-app/src/test

# Language specific settings
sonar.python.version=3.11
sonar.javascript.lcov.reportPaths=my-app/coverage/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/venv/**,**/dist/**,**/*.test.jsx,**/*.test.py
sonar.test.exclusions=**/tests/**,**/test/**

# Encoding
sonar.sourceEncoding=UTF-8
